### ISSUE TITLE
Triangular and uniform distributions don't seem to work in multimodals

### ISSUE THREAD

**Issue by OAGr** [foretold-app/widedomain#57]
<img width="1601" alt="image" src="https://user-images.githubusercontent.com/377065/86625481-07466700-bfbd-11ea-80ed-7ac38c81289c.png">

**Comment by skosch** [comment]
This seems to be a bug with how integrals are calculated, so it's not normalizing correctly and not finding the right xMin/xMax for plotting. Very strange.

**Comment by skosch** [comment]
Alright, looks like reverting to the old `interpolateX` function for Uniforms (with the barely-outside zero points) fixes it, because of how linear interpolation works. The one downside of using such 4-point uniforms is that they make for excessively smooth results when convolved, but let's not worry about that for now.

(Also, I realized why our convolution results were often so weirdly cut off – I forgot to normalize my Gaussians in the KDE part :facepalm: things like `lognormal(1,1) + lognormal(1,1)` look much better now.)

**Comment by OAGr** [comment]
Sounds good.
